### ISSUE TITLE
Nasze-kino.pl

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#10]
@podpis,
Czy zaczales sie bawic ta  wtyczka ,poniewasz od dwoch dni nie pokazuje wynikow wyszukiwania ,czy sama padla?
Ogladalem przystanek alaska i chcialbym dokaczyc,
Na incursion i fan film strasznie przycina

**Comment by podpis** [comment]
Wygläda na to, że strona Nasze-kino.pl jest down. Odczekać parę dni, a jak nie, tzn., że już policja była u właściciela strony. :)

**Comment by kopernik1983** [comment]
zraz policja. A może domena??? https://www.nasze-kino.eu/forum.php

**Comment by kopernik1983** [comment]
@wisiann  nasze-kino.tv lub www.nasze-kino.online ale ni pl :P co nie zmienia faktu że strony były ze soba powiązane i nie działa ani jedna ani druga :P

**Comment by krzysztof222** [comment]
działa

**Comment by podpis** [comment]
Już nie działa, wprowadzili zabezpieczenie Cloudflare. Tym samym stara wtyczka staje się bezużyteczna, trzeba wszystko przeprogramować.

**Comment by CrYpT0n1T3** [comment]
Nie wystarczy zmienić dns na cloudflarowe 1.1.1.1? ;D
