### ISSUE TITLE
Dodanie repozytorium jsergio123 => resolveurl

### ISSUE THREAD

**Issue by notoco** [podpis/kodi#16]
Ponieważ nie wszyscy korzystają z różnych przydatnych repozytoriów, może ze względu na fakt używania resolveurl (z repozytorium https://github.com/jsergio123) jako zależności, mógłbyś go dodać do repozytorium ?
```
<dir>
            <info compressed="false">https://raw.githubusercontent.com/jsergio123/zips/master/addons.xml</info>                                  <checksum>https://raw.githubusercontent.com/jsergio123/zips/master/addons.xml.md5</checksum>
            <datadir zip="true">https://raw.githubusercontent.com/jsergio123/zips/master/</datadir>
</dir>
```

**Comment by CrYpT0n1T3** [comment]
Dobry pomysł.. wszystko co potrzebne do wtyczek powinno być w jednym miejscu.

**Comment by podpis** [comment]
Załatwione!

**Comment by notoco** [comment]
Dobrze że wrzuciłeś u siebie, przy humorach Sergio nie wiadomo czy nie będzie problemów z dostępnością jego repozytorium... Może trzeba będzie się później przerzucić na urlresolver
