### ISSUE TITLE
Live polish tv

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#22]
@podpis,
Mowiles kiedys ze sie wezmiesz za te wtyczke.i zrobisz na nowo,
Praktycznie te wtyczki co rozkodowales wystarczja w zupelnosci do ogladania tego co sie chce ,jak ktos chce wiecej to FanFilm lite zalatwia sprawe do konca ,
Jak wspominalem wczesniej w usa ta wtyczka jest malo przydatna,wiekszosc pusta,blokowane sa streamy ze wzgledu na region i przesuniecie czasowe dobija temat,

Jak bedziesz chcial chlopca do testow to sie zglaszam 

Dzieki! 😎

**Comment by podpis** [comment]
Mam już wtyczkę LivePolishTV całkowicie rozkodowaną. Ale 70% źródeł jest już nieczynnych. Sam muszę wprowadzić nowe źródła i dopiero wtedy udostępnię tą wtyczkę. Wizja.tv to też jest jakieś nieporozumienie, albo zablokowali moją IP, albo działa tylko na kontach abonenckich. Muszę to jeszcze sprawdzić.

**Comment by wisiann** [comment]
Czekam z niecirpliwoscia na wyniki pracy ,
Jak juz pytalem,bedzie mozliwosc przesuniecia czasowego w live tv na usa?
Teraz jak chce cos poogladac to mam wrozbite Maraiana,albo Zofia chce mi cos sprzedac ,🤣

**Comment by xxcriticxx** [comment]
@wisiann tv z time shiftem to tylko platne $30 mies za 115 kanalow

**Comment by wisiann** [comment]
To ja wiem,ale jak by bylo na kodi to nie trzeba by bylo wykupowac 😀
