### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#25]
Zadna wtyczka nie dziala z podpis repo?
Czy to globalnie ,czy tylko u mine?

**Comment by podpis** [comment]
Kolego, Tylko u Ciebie! Co+ odinstalowałeś, pewnie script resolveurl.  :)

**Comment by wisiann** [comment]
Log,

https://paste.kodi.tv/voremegane

**Comment by wisiann** [comment]
Kurcze? Nic nie dotykalem?

**Comment by wisiann** [comment]
Sprawdzilem, 
Resolveurl jest w porzadku?

**Comment by wisiann** [comment]
Ok, cos jest nie tak na moim telefonie,
Sprawdzilem na Amazon box i wszystko dziala,
Sorry za niepotrzebne zamieszanie,

Wykasuje topic zaraz ,
Ale czy mogl bys zucic okiem na log?
Dlaczego tak jest? Zanim go wykasuje

**Comment by xulek** [comment]
Brakuje ci zależności script.module.requests bo masz resolver z cherrytv który jest modyfikowany pod build

**Comment by podpis** [comment]
Brakuje u Ciebie zależności script.module.requests, której potrzebuje script.module.resolveurl. Te rzeczy musisz zainstalować. Jak już kolega powyżej nadmienił, ktoś narobił ambarasu swoją wtyczką. Zamiast zmienić jej nazwę, to przepisał resolveurl swoją wersją i tym samym unieruchomił inne wtyczki.

**Comment by wisiann** [comment]
Dzieki, @xulek

Wlasnie zrobilem jego update z repo Podpis,i zaczelo dzialac

Nie wiem dlaczego ale nigdy nie uzywalem cherry tv do updates resolverurl,
Czy jest mozlive ze resolveurl sam decyduje.z ktorego repo sobie robic update?

**Comment by wisiann** [comment]
Dzieki @podpis,

**Comment by notoco** [comment]
@xulek - to może to poprawić? 

> Jak już kolega powyżej nadmienił, ktoś narobił ambarasu swoją wtyczką. Zamiast zmienić jej nazwę, to przepisał resolveurl swoją wersją i tym samym unieruchomił inne wtyczki.
