### ISSUE TITLE
Wtyczka nasze-kino.tv wyłączanie filmów.

### ISSUE THREAD

**Issue by dobosz23** [podpis/kodi#26]
Wielkie brawa za poprawę wtyczek.
Czy ktoś miał problem z instalacją ResolveUrl lub rozłączaniem działania filmu raz po 20 minutach, a raz po 30 minutach?Na wersji mod działało bez przerw. Myślałem że to wina Kodi, ale wszystko co mogłem poustawiałem i nic. Nie jest to wina też tego, że używam Kodi na Sony Android TV - wszystko inne działa ok no i wcześniejsze wtyczki funkcjonowały.

**Comment by podpis** [comment]
Działanie filmu po x czasie nie ma już nic wspólnego z wtyczką lub resolveurl, to wina tylko i wyłącznie samego playera lub źródła filmu. W Twoim przypadku pewnie to drugie, tzn. jest problem ze źródłem.

**Comment by dobosz23** [comment]
Też tak myślałem, ale testowałem kilka filmów z różnych źródeł i tak samo. Na początku miałem natomiast problem z instalacją ResolveUrl - za każdym razem pokazywało że instalacja nieudana. Dopiero zainstalowałem z zip, a później zainstalowałem repo jsergio i z wtyczkami ResolveUrl, bo myślałem że może o to chodzi. Chyba wyczyszczę Kodi i jeszcze raz zainstaluje wtyczki.

**Comment by dobosz23** [comment]
Po wyczyszczeniu Kodi zainstalowałem repo i nie chciało znowu zainstalować ResolveUrl. Dopiero jak zainstalowałem repo jsergio123 z wtyczkami. Będe teraz testowałem czy wszystko działa a jak możesz napisz co potrzeba by działał ResolveUrl. Może czegoś nie zainstalowałem co jest potrzebne?

**Comment by xulek** [comment]
Ponieważ repo Podpis nie zawiera wszystkich niezbędnych zależności i potrzeba do instalacji resolveurl innego repo np. jsergio. Można też poprosić Pospisa żeby uzupełnił repo o zależności :)

**Comment by podpis** [comment]
Kto+ tutaj pisał, że repo podpis nie zawiera wszystkich zależności. No to zajrzyjcie dokładnie do repo i przekonajcie się sami.

**Comment by xulek** [comment]
@podpis tak to ja, ale szybko się poprawiłem i usunąłem post, gdyż są oznaczone jako opcjonalne :)

**Comment by podpis** [comment]
Również to się nie zgadza, nie są oznaczone jako opcjonalne. <import addon="script.module.resolveurl" version="5.0.00"/> - czyli do poprzedniej wersji. Aktualna jest 5.0.09 i powinna zainstalować się z mojego repo.

**Comment by xulek** [comment]
Mówię o zależnościach :)

addons.xml

```
<addon id="script.module.resolveurl" name="ResolveURL" version="5.0.09" provider-name="jsergio">
	<requires>
		<import addon="xbmc.python" version="2.1.0" />
		<import addon="plugin.video.youtube" **optional="true"** />
		<import addon="script.module.python.twitch" **optional="true"** />
		<import addon="script.module.cryptopy" version="1.2.6" **optional="true"** />
		<import addon="plugin.video.gdrive" **optional="true"** />
```

**Comment by podpis** [comment]
To są ustawienia jsergio123, nie moje.

**Comment by xulek** [comment]
ale są w Twoim addons.xml więc tych wtyczek/skryptów, które tam są szuka w twoim repo jeśli nie ma żadnego innego zainstalowanego i nie są zaznaczone jako opcjonalne

**Comment by podpis** [comment]
Wszystkie opcjonalne wtyczki nie pochodzą z repo jsergio123.

**Comment by xulek** [comment]
dlatego są opcjonalne i nie wymagane do działania :) Ale to już napisałem. Więc to nie jest problem OP i najlepiej jakby wstawił log po nieudanej instalacji

**Comment by podpis** [comment]
Ja instalowałem - robiłem testy - na nagim KODI. Wszystko instalowało się bez żadnych błędów.

**Comment by dobosz23** [comment]
https://drive.google.com/file/d/1hk7ol37kG9oqA_-_3DGVoMXJExmm-eSP/view?usp=drivesdk

**Comment by dobosz23** [comment]
Niestety ja instaluje na trochę innej wersji Kodi ze zmodyfikowaną nazwą by działało 3D.

**Comment by podpis** [comment]
Ja również używam zmodyfikowanej wersji KODI z DSPPlayer i nawet na nie wszystkie wtyczki pracują bez problemu.

**Comment by podpis** [comment]
Jest problem z ładowaniem resolveurl z mojego repo. Tutaj jest problem: CCurlFile::Open failed with code 404 for https://github.com/podpis/kodi/raw/master/zips/script.module.resolveurl/script.module.resolveurl-5.0.09.zip

Sprawdzę jeszcze raz wszystkie ustawienia.

**Comment by notoco** [comment]
Masz zła nazwę folderu w zips. Ma być script.module.resolveurl a masz samo resolveurl. I się kodi gubi

**Comment by dobosz23** [comment]
Na wersji mod nic nie przerywało filmu a teraz za każdym razem - jeszcze razinstaluje Kodi i wtyczki.

**Comment by dobosz23** [comment]
Pokazuj mi przy instalacji ResolveUrl:

script.module.cryptopy
plugin.video.gdrive

Jako potrzebne ale niedostępne - może o to chodzi?

**Comment by dobosz23** [comment]
Z zipa mi zainstalowało ale nie wiem czy to może mieć wpływ na działanie filmów.

**Comment by dobosz23** [comment]
Rok 2018 film nr 11 źródło ostatnie po 12 lub 20 lub 30 minutach wychodzi do wyboru filmu - w czym tu jest problem.

**Comment by podpis** [comment]
Problem wersji KODI, której używasz.

**Comment by dobosz23** [comment]
Czyli jak bym nie ustawiał tego Kodi i tak mnie wyrzuci z odtwarzania?

**Comment by podpis** [comment]
Nie wiem, nie testowałem wtyczek na wersji, której używasz.

**Comment by dobosz23** [comment]
A na której na pewno działają prawidłowo?

**Comment by podpis** [comment]
Na Androidzie mam dobre doświadczenia z wersjami KODI "SPMC" i KD PLAYER. Chodzą lepiej od standardowych.

**Comment by dobosz23** [comment]
Dziękuję za pomoc.

**Comment by dobosz23** [comment]
Na oryginalnej sprawdziłem i było to samo. Jutro sprawdzę SPMC - może mojemu Tv poprostu jest potrzebny reset do fabrycznych

**Comment by podpis** [comment]
Pomimo tego, to nie jest problem wtyczek, ani resolverurl.

**Comment by dobosz23** [comment]
Teraz sam też jestem o tym przekonany.
