### ISSUE TITLE
script.module.requests - dodaj jako zależność do wtyczek które korzystają

### ISSUE THREAD

**Issue by notoco** [podpis/kodi#27]
Dodaj script.module.requests jako zależność do wtyczek które masz w repo - łatwiej będzie to ogarnąć wszystko przy różnych źródłach resolvera i różnych konfiguracjach.

**Comment by podpis** [comment]
Nie ma potrzeby, script.module.request jest już zawarty w oficjalnym repo KODI. Sprawdzałem i dlatego nie wrzuciłem do mojego. :)

![request](https://user-images.githubusercontent.com/24512556/40447546-381e51b4-5ed3-11e8-8941-dbbf3a9827e0.PNG)

**Comment by podpis** [comment]
Dodam jeszcze, że gdybym prędzej wiedział o możliwościach tego modułu, to bym nie babrał się tyle czasu z urllib, urllib2 i httplib2. :)

**Comment by notoco** [comment]
Nie chodzi mi o dodanie do repo, tylko do pliku addon.xml wtyczki alltube i zalukaj bo nawet na oryginalnym resolver nie chcą się uruchamiać, a on tego też nie zaciąga. Pomaga dopiero instalacja innych wtyczek które mają to w zależności.

**Comment by notoco** [comment]
Ok - jest dodane jako zależność w repo cherry, ja też tymczasowo dodałem do siebie...
Także już powinno działać.
