### ISSUE TITLE
Nasze-kino.tv

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#28]
Od paru dni co chwile nie dziala?

To wtyczka czy stronka?🤔

**Comment by notoco** [comment]
Na stronce przy obciążeniu (?) pojawia się cloudflare. Czy na stałe? Czy zniknie? Czy podpis poprawi? Tysiące pytań...

**Comment by podpis** [comment]
Zgadza się. Ten weekend mam niestety zajęty, muszę inny projekt doprowadzić do Końca.

**Comment by FXcodi** [comment]
Prosił bym także o poprawę urlresolver, ponieważ większość filmów i seriali np z alltube.tv oraz innych serwisów z tego repozytorium nie działa.

**Comment by notoco** [comment]
Alltube nie działa nie z powodu resolvera, ale z powodu zmian na stronie. Większość stron może mieć problemy obecnie ze względu na zmiany które wprowadzili w związku z RODO.

**Comment by FXcodi** [comment]
Czyli u was też nic nie chce działać a ja myślałem, że u mnie tylko. 
Szkoda że wcześniej nikt o tym nie wspomniał - a ja tyle czasu straciłem na kasowaniu i instalowanie różnych wtyczek, 
oraz kilka resetów androida oraz kodi.

**Comment by Marcin9246** [comment]
będzie działać repozytoria

**Comment by wisiann** [comment]
Sopko
