### ISSUE TITLE
Kontrybuowanie

### ISSUE THREAD

**Issue by pgrzesiecki** [podpis/kodi#34]
Jestem pełen podziwu dla projektu i sam z niego chętnie korzystam. Patrząc w kod chciałbym również wnieść coś od siebie i poprawić działanie niektórych rozszerzeń. Tutaj moje pytanie, w jaki sposób mogę wrzucić PR np. dla paczki zalukaj, która w repo jest umieszczona w formacie zip? Istnieje osobne repo na kod źródłowy pluginów? Może dobrym pomysłem byłoby umieszczenie go obok paczek zip do wglądu dla innych i ewentualnego kontrybuowania?

**Comment by podpis** [comment]
Każdy może wprowadzać zmiany i w spakowanej formie wrzucać tutaj na issue. Po sprawdzeniu i akceptacji nowa wersja zostanie wstawiona do repo.
O kodzie źródłowym pomyślę...
