### ISSUE TITLE
Chętnych programistów zapraszam do współpracy przy rozwoju i pielęgnacji wtyczek

### ISSUE THREAD

**Issue by neopack1** [podpis/kodi#39]
....hmmm
Fork od tego pedałka... Spoko...
Domyślam się, że rozgryzłeś kodowani skryptów w plikach py 👍 
... ewentualnie mogę pomóc użyczając prywatne API dekodujące te robaczki...

a skoro szukasz chętnych do zabawy...
..skoro nalegasz, .to się zgłaszam 🆘
maczałem palce przy większości polskich wtyczek,
dodałem również polskie serwisy do mało znanego
pluginu "exodus" - fork: "covenant" a tak z nudów pomagam
chłopakom z 'Vashiel' przy 'AdultHideout' :P
no i troszkę na iptv.zone sniffując polskie zakresy ip.
Ogólnie sam sobie piszę wtyczki na własne potrzeby ale...
w temacie ROZJEBANIA ramic'a zgłaszam się do pierwszej linii!

odezwij się to pogadamy...

**Comment by podpis** [comment]
Jest kilku, którzy pomagają. Każdy programista się przyda. Jest jeszcze cała paleta nierozkodowanych wtyczek.  N.p. plugin.video.cdahd, plugin.video.cdapl, plugin.video.cdaxpl. Możesz się tym zająć? Ja robię parę innych, ale są mistrzostwa...

**Comment by meserak86** [comment]
radzil bym zaczekac do protestow w sprawie 11/13 bos ie moze okazac ze tak naprawde za chwile nie bedzie po co robic wtyczek i bedziemy kupowac netflixa

**Comment by Janasek** [comment]
_@neopack1_  może zanim zaczniesz zabawe z ramikiem to cos z **vectra.tvonline** byś zrobił logowanie jakieś vpn z logowaniem **coś coś**
