### ISSUE TITLE
Gdzie / Skąd 

### ISSUE THREAD

**Issue by adamibeata** [podpis/kodi#46]
Ja mam takie pytanie gdzie są dostępne wszystkie wtyczki  lub z skąd można je pobrać

**Comment by notoco** [comment]
Wszystkie wtyczki są dostepne w internecie i stamtąd można je pobrać. A na powagę - zerknij na kodiwpigulce.pl znajdziesz tam wiele informacji.

**Comment by adamibeata** [comment]
czyli tak naprawde nie ma nic

**Comment by xulek** [comment]
No niestety nie ma nic. Mam nadzieję, że pomogłem :) 

@notoco skąd ci ludzie się biorą.. haha :D
