### ISSUE TITLE
nasze-kino.tv przestalo dzialac

### ISSUE THREAD

**Issue by tomusfl** [podpis/kodi#51]
Jakies zmiany na stronie?
teraz wtyczka znowu prosi o wpisanie kodu z obrazka i po wpisaniu kodu niestey twierdzi ze kod jest niewlasciwy, probowalem kilka razy zawsze to samo., 
versia  wtyczki 1.6.2
kodi 17.6 
android

**Comment by dmxcasper2** [comment]
Mam ten Sam problem. Capchta nie uznaje kodu wprowadzonych podczas verifikacji.

Strona nasze kino musiało coś zmienić na swojej stronie.

**Comment by podpis** [comment]
Problem jest następujący: blokada Cloudflare i Captcha, która niestety również ładowana jest przez Cloudflare.

**Comment by wisiann** [comment]
A tak bylo pieknie !!😢

**Comment by mbebe** [comment]
Od wczoraj cloudflare jest zdjety, wtyczka tez akceptuje captche.

**Comment by xxcriticxx** [comment]
jak by ktos nie widzial obrazka captche trzeba zaznaczyc grupuj epizody w sezonach w opcjach wtyczki

**Comment by wisiann** [comment]
@mbebe ..thanks!

**Comment by mbebe** [comment]
Podalem tylko informacje. We wtyczce nie bylo zmian. :-D

**Comment by dmxcasper2** [comment]
U mnie też przestało działać dzisiaj. Hyba problem z serwerem nasze kino.

**Comment by kashkash18** [comment]
Wszystko wróciło do normy

**Comment by FXcodi** [comment]
Nasze-kino.tv jak dzisiaj patrzę, to nie chce mi odpalać żadnego filmu.
A jak sytuacja wygląda u was?. 
Może jakaś aktualizacja?.
Czy to tylko u mnie taki problem jest.

**Comment by xxcriticxx** [comment]
@FXcodi linky pozamykane `http://adf.ly/3554668/http://adf.ly/3554668/banner/https://www.nasze-kino.tv` ktos kase na reklamach kasuje

@mbebe help!

**Comment by papulus** [comment]
Mam to samo

**Comment by papulus** [comment]
Znacie moze cos podobnego do nasze kino tv?

**Comment by FXcodi** [comment]
A może by tak zrobić wtyczkę allbox.tv?.
Tam też można pooglądać fajne filmy i jest też sporo nowości.

**Comment by ciwy85** [comment]
od kilku dni juz nie dziala, zna ktos dobra alternatywe dla polskich seriali?

**Comment by mbebe** [comment]
teraz widze, ze wylaczyli naszekino - moze na chwile.

`Database connection could not be established.`

videopenny.net - dla polskich seriali

**Comment by kashkash18** [comment]
To może wtyka videopenny

**Comment by mbebe** [comment]
poprawne streamy.
[plugin.video.naszekinotv-1.6.3.zip](https://github.com/podpis/kodi/files/2452193/plugin.video.naszekinotv-1.6.3.zip)

**Comment by dmxcasper2** [comment]
Wersja 1.6.3 poprawiła linki ale teraz captcha nie rejestruje właściwie wprowadzonego kodu. Nawet po wprowadzeniu właściwego kodu, wyskakuję błąd że lód jest źle wprowadzony.

**Comment by papulus** [comment]
mbebe uzylem twoj zip file do naszekinotv I wszystko pracowalo tylko na jednym filmie  a potem Tak Jak poprzednio nie jaduje streamow

**Comment by ciwy85** [comment]
potwierdzam 1.6.3. captcha nie rejestruje poprawnie wprowadzonego kodu

**Comment by kendo999** [comment]
nasze-kino.tv nie wyswietlają się okladki filmow mozna porawkie

**Comment by kashkash18** [comment]
To do okładek może jeszcze opisy które nie spowalniają wtyczki. Podpis dał opcje opisów ale po jej włączeniu wtyczka działa bardzo wolno.

**Comment by ciwy85** [comment]
Czy wtyczka/strona padla na dobre?

**Comment by mbebe** [comment]
wtyczka nie wyswietla filmow, nie odpala filmow, czy co?

**Comment by mbebe** [comment]
tu tez poszla poprawka

**Comment by papulus** [comment]
Witam , wtyczka nasze kino działa tylko z filmami . Nie wyświetla linków jeśli chodzi o seriale. Czy mógłby ktoś na to spojrzeć?

**Comment by ciwy85** [comment]
1.6.5 działa ok, sprawdziłem dwa seriale i nie było problemu z linkami

**Comment by papulus** [comment]
ciwy85 masz rację 1.6.5 działa ok miałem wersje 1.6.6 a wtej wersji seriale nie dzialaja

**Comment by kendo999** [comment]
można poprawkie  okładek filmow

**Comment by mbebe** [comment]
poprawka do okladek (oprocz listy seriali) u mnie w repo.
wersja 1.6.7

**Comment by kashkash18** [comment]
A jest szansa na opisy filmów bez zwalniania wtyczki ??

**Comment by papulus** [comment]
mbebe nasz kino w wersji 1.6.7 dalej nie wyświetla linków do seriali. Można by coś z tym zrobić?

**Comment by papulus** [comment]
Kodi 17.6

**Comment by papulus** [comment]
I na każdym seriali

**Comment by ciwy85** [comment]
sprawdzilem 1.6.7 z mbebe repo i dzialaja seriale, upewnij sie ze zaznaczyles w ustawieniach wtyczki "grupuj epizody w sezonach" na przynajmniej jedno wyszukanie pozniej mozesz to odznaczyc, jest to stary "bug" przez ktory nie wyswietla sie kod captcha.

**Comment by mbebe** [comment]
mimo wszystko dalem update na 1.6.8

**Comment by papulus** [comment]
1.6.8 wszystko działa .

**Comment by tomusfl** [comment]
dziala

**Comment by Damianx39** [comment]
Nasze-Kino od dzisiaj nie dziala :-(

**Comment by kashkash18** [comment]
Nie działa gdyż witryna jest nieosiągalna.
