### ISSUE TITLE
cda-hd

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#52]
W zakladce z serialami pojawiaja sie te same pozycje co w zakladce z filmami, 
Czy to tylko w usa?

**Comment by mbebe** [comment]
Zmieniono cos na stronie. Mam tak samo.

**Comment by mbebe** [comment]
[plugin.video.cdahd-1.6.1.zip](https://github.com/podpis/kodi/files/2225610/plugin.video.cdahd-1.6.1.zip)
- host name
- search fix
Nie dzialalo u mnie szukanie, wiec zmienilem na requests.
Sprawdzcie.

**Comment by xxcriticxx** [comment]
@mbebe dasz radę dodać jakieś nowe resolvery do polskich stron?

@wisiann pozdrawiam

**Comment by wisiann** [comment]
Siema @xxcriticxx

**Comment by wisiann** [comment]
@mbebe ..dzieki,wrocilo do normy,
