### ISSUE TITLE
plugin.video.LivePolishTV-2.5.8.zip - error

### ISSUE THREAD

**Issue by MarkekJankowski** [podpis/kodi#6]
Próbowałem instalować z plugin.video.LivePolishTV-2.5.8.zip i dostaje error ze script.module.ramic ma problem....  czy są jakieś instrukcje jak zainstalować ten addon

**Comment by podpis** [comment]
Proszę najpierw zainstalować script.module.ramic: https://github.com/podpis/kodi/blob/master/zips/script.module.ramic-1.2.8.zip
Bez tego ta wersja nie poleci. Następna wersja nie będzie już używała tego skryptu.
