### ISSUE TITLE
Ekstraklasa.tv

### ISSUE THREAD

**Issue by farbenh** [podpis/kodi#68]
Komunikat o niedostępności video spoza Polski mimo odtwarzania z Polski.

"Sorry, but this video clip is presently unavailable to users outside of Poland"

Jest tak tylko u mnie czy u wszystkich?

Edit: ok widzę że są nowe wersje wtyczki a w repo jeszcze stara wersja. Temat zamykam.

**Comment by farbenh** [comment]
Może nowe repo jako kontynuacja?

**Comment by kashkash18** [comment]
To by było najlepsze rozwiązanie. Pisałem kiedyś o tym gdzieś , ale @mbebe woli takie rozwiązanie jakie jest teraz . Może kiedyś się zdecyduje na taki ruch . Gdyby nie on to nie było by połowy wtyczek , a do tego zajmuje się wszelkimi fixami i podsuniętymi pomysłami za co mu chwała .
