### ISSUE TITLE
Nasze-kino.tv

### ISSUE THREAD

**Issue by wisiann** [podpis/kodi#73]
Cos sie dzieje z captcha ,
Po wpisaniu kodu dalej pyta czy jestes czlowiekiem,
Macie to samo?

**Comment by wisiann** [comment]
@mbebe,
Zucisz na to okiem w wolnej chwili?

**Comment by mbebe** [comment]
captcha po ostatnich zmianach byla za cloudflare
[plugin.video.naszekinotv-1.6.4.zip](https://github.com/podpis/kodi/files/2454090/plugin.video.naszekinotv-1.6.4.zip)

**Comment by wisiann** [comment]
@mbebe,
Nie pokazuje zrodel,

**Comment by FXcodi** [comment]
U mnie działa.

**Comment by oliwer12345** [comment]
cz napewno jestes czlowiekiem tak pokazuje po wpisaniu hasla

**Comment by FXcodi** [comment]
Sprawdziłem przed chwilą i wyskakuje pusty host.
Wczoraj działało normalnie.

**Comment by mbebe** [comment]
poprawka
[plugin.video.naszekinotv-1.6.5.zip](https://github.com/podpis/kodi/files/2455635/plugin.video.naszekinotv-1.6.5.zip)

**Comment by papulus** [comment]
1.6.5 dziala poprawnie

**Comment by ciwy85** [comment]
dziala dziala, mozna dodawac do repo :)

**Comment by krecik71** [comment]
dodane :)
