### ISSUE TITLE
Lambda Sources

### ISSUE THREAD

**Issue by xxcriticxx** [podpis/kodi#80]
script.module.lambdascrapers - 1.6.0

Added German and **Polish providers**

testowal ktos?

@notoco check it out and report back

**Comment by notoco** [comment]
Nie używam. Ale patrząc na szybko to tam ciągle wisi trt i brak wielu które są w fanfilm. Podejrzewam że podebrane z innej wtyczki...

**Comment by kopernik1983** [comment]
Nada się ale nie do polskich źródeł. We wtyczkach bodaj Exodus Redux i Magicality można w opcjach sobie ustawić tego scraperka i potestować. Jak komuś się nudzi :)
