### ISSUE TITLE
kodiwpigulce.pl

### ISSUE THREAD

**Issue by xxcriticxx** [podpis/kodi#81]
@notoco nie mozna sie zalogowac do konta

![capture](https://user-images.githubusercontent.com/15007183/47994857-93eea280-e0c1-11e8-80d0-345cabddbf38.PNG)

**Comment by xxcriticxx** [comment]
cc @kodiwpigulce

**Comment by xxcriticxx** [comment]
@notoco dokladnie juz dziala

**Comment by kodiwpigulce** [comment]
@xxcriticxx hosting coś od rana świruje ale powinno być już dobrze ;)

**Comment by xxcriticxx** [comment]
@kodiwpigulce witamy na githubie!
