### ISSUE TITLE
Seren

### ISSUE THREAD

**Issue by xxcriticxx** [podpis/kodi#83]
@podpis / @rysson / @mbebe / @notoco  / @xulek 

https://nixgates.github.io/packages/

https://www.reddit.com/r/Addons4Kodi/comments/9z0hwj/seren_setup_guide_its_finally_here/

**Comment by notoco** [comment]
Wiemy, widzieliśmy, na razie tylko działa z premium.

**Comment by xulek** [comment]
Brakuje w zależnościach resolvera, nie ma funkcji resolvującej zwykłe linki, tłumaczenie stringów jest zrobione(albo raczej nie zrobione) w stylu hard code mimo, że jest stworzona biblioteka języków, do dodanych scrapperów nie da się podłączyć opcji do settings np. danych logowania i trzeba to robić bezpośrednio w scrapperach. Wtyczka musi przejść jeszcze gruntowne zmiany żeby można było wygodnie coś z nią konkretnego zrobić
