### ISSUE TITLE
Wizja.Tv Premium Nie Działa 

### ISSUE THREAD

**Issue by Huero23** [podpis/kodi#88]
Żadne kanał nie wchodzą?

**Comment by Maro1982** [comment]
Strona padla chyba Koniec WizjaTV

**Comment by QwerkoooN** [comment]
Kiedy ta strona padła?

**Comment by Huero23** [comment]
@QwerkoooN WizjaTv padła parę miesięcy temu dużo ludzi jeszcze miało aktywne Premium. Jest jeszcze HEJO.TV & INTERNETOWA.TV
